name: Build and test Go projects

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build go-server project
      run: |
        cd ./go-server/
        go build 
        
    - name: Build go-docker project
      run: |
        cd ./go-docker/
        go build 
    
    - name: Build go-email-checker project
      run: |
        cd ./go-email-checker/
        go build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Test go-server project
      run: |
        cd ./go-server/
        go clean --testcache && go test

    - name: Test go-docker project
      run: |
        cd ./go-docker/
        go clean --testcache && go test
        
    - name: Test go-email-checker project
      run: |
        cd ./go-email-checker/
        go clean --testcache && go test
